# Generated by Django 2.2.24 on 2021-12-24 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evangelisation', '0002_auto_20211221_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivi',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='evangelisation.Person', verbose_name='Personne'),
        ),
    ]
